version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-ai
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgres/data
